version: "3.8"

services:
  database:
    image: mariadb:10.6
    container_name: nextcloud-database
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 7778:80
    links:
      - database
    volumes:
      # - opt/ext-storage:/var/www/html
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=database

volumes:
  nextcloud:
  db:
