version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: nginx-status-check
    ports:
      - "7777:80"
    volumes:
      - ./nginx/www:/usr/share/nginx/html/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
