version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - volum:/volum:rw
      - ./things/nginx/www:/volum/nginx/www
      - ./things/nginx/conf.d:/etc/nginx/conf.d
      
      - ./things/certbot/conf:/etc/letsencrypt
      - ./things/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - volum:/volum:rw
      - ./things/certbot/conf:/etc/letsencrypt
      - ./things/certbot/www:/var/www/certbot
volumes:
  volum:
