version: "3.8"

services:
  jellyfin-server:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=domain.com
    volumes:
      - /fiml/folder:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
